### HobbyFarm Settings and Configurations
apiVersion: hobbyfarm.io/v1
kind: Environment
metadata:
  name: aws-env
  namespace: hobbyfarm-system
spec:
  count_capacity:
    rocky-9.2: 500
    ubuntu-22.04: 500
    sles-15-sp4: 500
    rhel-9.1: 500
    centos-7.8: 500
    aws-al2023: 500
    aws-al2: 500
  display_name: aws-env
  dnssuffix: null
  ip_translation_map: null
  environment_specifics:
    cred_secret: aws-creds
    executor_image: rancher/terraform-controller-executor:v0.0.13-alpha1
    module: tf-module-aws
    region: us-east-1
    subnet: subnet-0ca6bea3c0d18b6f3
    vpc_security_group_id: sg-0c87eb1835fdbb24f
  provider: aws
  template_mapping:
    rocky-9.2:
      disk: "64"
      image: ami-09c77dc92e45bc3ea
      instance_type: m5a.2xlarge
      ssh_username: rocky
    ubuntu-22.04:
      disk: "64"
      image: ami-053b0d53c279acc90
      instance_type: m5a.2xlarge
      ssh_username: ubuntu
    sles-15-sp4:
      disk: "64"
      image: ami-021b67c90e3e68a8f
      instance_type: m5a.2xlarge
      ssh_username: ec2-user
    rhel-9.1:
      disk: "64"
      image: ami-04d2290c1e193d4c7
      instance_type: m5a.2xlarge
      ssh_username: ec2-user
    centos-7.8:
      disk: "64"
      image: ami-0aedf6b1cb669b4c7
      instance_type: m5a.2xlarge
      ssh_username: centos
    aws-al2023:
      disk: "64"
      image: ami-0f34c5ae932e6f0e4
      instance_type: m5a.2xlarge
      ssh_username: ec2-user
    aws-al2:
      disk: "64"
      image: ami-0f9ce67dcf718d332
      instance_type: m5a.2xlarge
      ssh_username: ec2-user
  ws_endpoint: hobbyfarm-shell.aws.rancher.lol
---
apiVersion: terraformcontroller.cattle.io/v1
kind: Module
metadata:
  name: tf-module-aws
  namespace: hobbyfarm-system
spec:
  git:
    branch: master
    intervalSeconds: 1800
    url: https://github.com/hobbyfarm/tf-module-aws
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: rocky-9.2
  namespace: hobbyfarm-system
spec:
  name: rocky-linux-9.2
  image: ami-09c77dc92e45bc3ea
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: ubuntu-22.04
  namespace: hobbyfarm-system
spec:
  name: ubuntu-lts-22.04
  image: ami-053b0d53c279acc90
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: sles-15-sp4
  namespace: hobbyfarm-system
spec:
  name: suse-sles-15-sp4
  image: ami-021b67c90e3e68a8f
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: rhel-9.1
  namespace: hobbyfarm-system
spec:
  name: redhat-rhel-9.1
  image: ami-04d2290c1e193d4c7
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: centos-7.8
  namespace: hobbyfarm-system
spec:
  name: centos-linux-7.8
  image: ami-0aedf6b1cb669b4c7
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: aws-al2023
  namespace: hobbyfarm-system
spec:
  name: aws-amazon-linux-2023
  image: ami-0f34c5ae932e6f0e4
  config_map:
    cloud-config: ""
    webinterfaces: '[]'
---
apiVersion: hobbyfarm.io/v1
kind: VirtualMachineTemplate
metadata:
  name: aws-al2
  namespace: hobbyfarm-system
spec:
  name: aws-amazon-linux-2
  image: ami-0f9ce67dcf718d332
  config_map:
    cloud-config: ""
    webinterfaces: '[]'